### ISSUE TITLE
Difficulty in Running SST2 Example

### ISSUE THREAD

**Issue by jbrry** [ibm-granite/dolomite-engine#36]
Hi there, thank you for the nice resource!

I am trying to familiarise myself with dolomite-engine.

If I try to run the sst2 example:
`./scripts/pretrain.sh configs/sst2/training.yml`

The default values in `configs/sst2/training.yml` will cause AssertionErrors [here](https://github.com/ibm-granite/dolomite-engine/blob/79bb8f1a7b34dc6ae88de153e6ce5b2e121264e0/dolomite_engine/data/megatron/__init__.py#L23).

After manually changing and removing some parameters in the yaml file, I think when not specifying data locally, e.g. with `class_args.data_path`, it is not triggering the conditions [here](https://github.com/ibm-granite/dolomite-engine/blob/79bb8f1a7b34dc6ae88de153e6ce5b2e121264e0/dolomite_engine/data/megatron/__init__.py#L91).

Ultimately, I would like to finetune a model on jsonlines data like in the form specified in the [README](https://github.com/ibm-granite/dolomite-engine/tree/main?tab=readme-ov-file#dataset) so if you have any pointers on the most relevant configs for that, it would be really helpful too.

**Comment by mayank31398** [comment]
Yikes!!!
you need to run via `scripts/finetune.sh`.
I think its not well documented maybe, sorry for that.
Feel free to open a PR to add documentation for this if you want :)

**Comment by jbrry** [comment]
Ah my bad! I assumed `train.sh` in the following had changed name to `pretrain.sh`
`sh scripts/train.sh configs/sst2/training.yml`.

I can now run the finetuning entry-point using `DebugDataset`. I will now try with some local files.

BTW: would this repo support training models such as the Granite-series from scratch via the `pretrain` script, or is it more intended for finetuning such models?

Thanks, I will open up some issues/PRs if I see anything :)

**Comment by mayank31398** [comment]
its original purpose was just finetuning but I am adding large scale pretraining support (efficiently) on hundreds of GPUs.
So, watch out...
It will support both in the coming days

**Comment by jbrry** [comment]
Amazing thanks! It will be great to have this all in the one place, excited for what's in store!
